## **Mount Drive**

In [ ]:
from google.colab import drive
from google.colab import files
print("Getting Data from Google drive")
drive.mount('/content/drive/', force_remount ="True")

Getting Data from Google drive
Mounted at /content/drive/


## **Read Data**

In [ ]:
import numpy as nm  
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as mtp  
import pandas as pd  
data_set= pd.read_csv('/content/drive/MyDrive/BTP/kddcup.data.csv') 
#data_Set = data_set.dropna('columns')
x= data_set.iloc[:, 0:41].values 
y= data_set.iloc[:, 41].values  
d = {}
# Counting data poihnts of each class
for val in y:
  if val in d:
    d[val] = d[val]+1
  else:
    d[val] = 1

print(d)

from sklearn.preprocessing import LabelEncoder  
label_encoder_x1= LabelEncoder()  
label_encoder_x2= LabelEncoder() 
label_encoder_x3= LabelEncoder()  
    
x[:, 1]= label_encoder_x1.fit_transform(x[:, 1])  
x[:, 2]= label_encoder_x2.fit_transform(x[:, 2])  
x[:, 3]= label_encoder_x3.fit_transform(x[:, 3]) 

attack_class = {'normal.': 'Normal', 'back.': 'DOS', 'smurf.':'DOS', 'neptune.':'DOS', 'pod.': 'DOS', 'teardrop.':'DOS', 'land.': 'DOS',
                'multihop.':'R2L', 'ftp_write.': 'R2L', 'guess_passwd.': 'R2L', 'imap.': 'R2L', 'phf.': 'R2L', 'spy.':'R2L', 'warezmaster.':'R2L', 'warezclient.':'R2L',
                'rootkit.':'U2R', 'loadmodule.':'U2R', 'buffer_overflow.': 'U2R', 'perl.': 'U2R',
                'portsweep.':'PROBE', 'satan.':'PROBE', 'ipsweep.': 'PROBE', 'nmap.':'PROBE'}

 



for i in range(len(y)):
  y[i] = attack_class[y[i]]

#for i in range(len(y_test)):
#  y[i] = attack_class[y_test[i]]


for i in range(len(y)):
  if y[i] == 'Normal':
    y[i] = 0
  else:
    y[i] = 1



{'normal.': 972780, 'buffer_overflow.': 30, 'loadmodule.': 9, 'perl.': 3, 'neptune.': 1072017, 'smurf.': 2807886, 'guess_passwd.': 53, 'pod.': 264, 'teardrop.': 979, 'portsweep.': 10413, 'ipsweep.': 12481, 'land.': 21, 'ftp_write.': 8, 'back.': 2203, 'imap.': 12, 'satan.': 15892, 'phf.': 4, 'nmap.': 2316, 'multihop.': 7, 'warezmaster.': 20, 'warezclient.': 1020, 'spy.': 2, 'rootkit.': 10}


## **Encode and Split Data**

In [ ]:
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder

In [ ]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, dummy_y, test_size= 0.30, random_state=0)

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.30, random_state=0)

## **Binary (2 Classes) Classification**

In [ ]:
from keras.models import Sequential

# Import `Dense` from `keras.layers`
from keras.layers import Dense
model = Sequential()
model.add(Dense(12, input_dim=41, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Training

In [ ]:
import numpy as np
import time
#y_train = np.asarray(y_train).astype('float32')
#x_train = np.asarray(x_train).astype('float32')
time_start = time.time()
model.fit(x_train, y_train, epochs=10, batch_size=10)
time_end = time.time()
print("Training time: ", time_end - time_start)

Epoch 1/10
342891/342891 [==============================] - 401s 1ms/step - loss: 1.3140 - accuracy: 0.9962
Epoch 2/10
342891/342891 [==============================] - 401s 1ms/step - loss: 1.0707 - accuracy: 0.9988
Epoch 3/10
342891/342891 [==============================] - 401s 1ms/step - loss: 2.2420 - accuracy: 0.9987
Epoch 4/10
342891/342891 [==============================] - 400s 1ms/step - loss: 80.2555 - accuracy: 0.9988
Epoch 5/10
342891/342891 [==============================] - 400s 1ms/step - loss: 15.8719 - accuracy: 0.9984
Epoch 6/10
342891/342891 [==============================] - 400s 1ms/step - loss: 0.0082 - accuracy: 0.9989
Epoch 7/10
342891/342891 [==============================] - 401s 1ms/step - loss: 0.0080 - accuracy: 0.9990
Epoch 8/10
342891/342891 [==============================] - 403s 1ms/step - loss: 0.0067 - accuracy: 0.9990
Epoch 9/10
342891/342891 [==============================] - 402s 1ms/step - loss: 0.0069 - accuracy: 0.9991
Epoch 10/10
342891/342891 

# Testing

In [ ]:
y_test = np.asarray(y_test).astype('float32')
x_test = np.asarray(x_test).astype('float32')

In [ ]:
_, accuracy = model.evaluate(x_test, y_test)

45923/45923 [==============================] - 39s 854us/step - loss: 3.6912 - accuracy: 0.9989


In [ ]:
print("Accuracy: ", accuracy)

Accuracy:  0.9988723993301392


In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score, classification_report
time_start = time.time()
y_pred = model.predict(x_test)
time_end = time.time()
print("Testing time: ", time_end - time_start)
d = {}
y_pred = [int(y1[0]) for y1 in y_pred]
#y_pred = [int(y[0]) for y in y_pred]
y_test = [int(y1) for y1 in y_test]
#y_pred = np.argmax(y_pred, axis=1)
#y_test = np.argmax(y_test, axis=1)
for y in y_pred:
  if y in d:
    d[y] = d[y] + 1
  else:
    d[y] = 1
print(d)



#print(y_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Testing time:  24.11117434501648
{1: 1166075, 0: 303454}
[[ 291707       3]
 [  11747 1166072]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98    291710
           1       1.00      0.99      0.99   1177819

    accuracy                           0.99   1469529
   macro avg       0.98      1.00      0.99   1469529
weighted avg       0.99      0.99      0.99   1469529



## **5 Classes Classification**

In [ ]:
from keras.models import Sequential

# Import `Dense` from `keras.layers`
from keras.layers import Dense
model = Sequential()
model.add(Dense(12, input_dim=41, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(5, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

## Training



In [ ]:
import numpy as np
import time


y_train = np.asarray(y_train).astype('float32')
x_train = np.asarray(x_train).astype('float32')
print(y_train[:10])
time_start = time.time()
model.fit(x_train, y_train, epochs=10, batch_size=10)
time_end = time.time()
print("Training time: ", time_end - time_start)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
Epoch 1/10
342891/342891 [==============================] - 376s 1ms/step - loss: 3.0519 - accuracy: 0.9952
Epoch 2/10
342891/342891 [==============================] - 379s 1ms/step - loss: 5.3706 - accuracy: 0.9987
Epoch 3/10
342891/342891 [==============================] - 380s 1ms/step - loss: 8.7268 - accuracy: 0.9988
Epoch 4/10
342891/342891 [==============================] - 382s 1ms/step - loss: 35.6947 - accuracy: 0.9988
Epoch 5/10
342891/342891 [==============================] - 382s 1ms/step - loss: 19.9122 - accuracy: 0.9987
Epoch 6/10
342891/342891 [==============================] - 377s 1ms/step - loss: 49.2260 - accuracy: 0.9988
Epoch 7/10
342891/342891 [==============================] - 379s 1ms/step - loss: 3.3860 - accuracy: 0.9987
Epoch 8/10
342891/342891 [==============================] - 

# Testing

In [ ]:
y_test = np.asarray(y_test).astype('float32')
x_test = np.asarray(x_test).astype('float32')

In [ ]:
_, accuracy = model.evaluate(x_test, y_test)

45923/45923 [==============================] - 45s 985us/step - loss: 0.0095 - accuracy: 0.9988


In [ ]:
print("Accuracy: ", accuracy)

Accuracy:  0.9988105297088623


In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score, classification_report
time_start = time.time()
y_pred = model.predict(x_test)
time_end = time.time()
print("Testing time: ", time_end - time_start)
d = {}
y_pred = np.argmax(y_pred, axis=1)
y_test = np.argmax(y_test, axis=1)
for y in y_pred:
  if y in d:
    d[y] = d[y] + 1
  else:
    d[y] = 1
print(d)
#y_pred = [int(y[0]) for y in y_pred]
#y_pred = [int(y[0]) for y in y_pred]
#y_test = [int(y) for y in y_test]


print(y_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Testing time:  27.395376205444336
{0: 1164351, 1: 293375, 2: 11803}
[0 0 0 ... 0 1 1]
[[1164333     904       4       0       0]
 [     13  291674      23       0       0]
 [      4     468   11774       0       0]
 [      1     313       2       0       0]
 [      0      16       0       0       0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1165241
           1       0.99      1.00      1.00    291710
           2       1.00      0.96      0.98     12246
           3       0.00      0.00      0.00       316
           4       0.00      0.00      0.00        16

    accuracy                           1.00   1469529
   macro avg       0.60      0.59      0.60   1469529
weighted avg       1.00      1.00      1.00   1469529

